#
#
#================================================================
#   
#   
#   文件名称：config.mk
#   创 建 者：肖飞
#   创建日期：2021年08月26日 星期四 11时10分19秒
#   修改日期：2023年02月21日 星期二 11时38分51秒
#   描    述：
#
#================================================================

CONFIG_LIST := 

#CONFIG_LIST += USER_APP
#CONFIG_LIST += PSEUDO_ENV

CONFIG_LIST += IAP_INTERNAL_FLASH

CONFIG_LIST += DEVICE_TYPE_DC

CONFIG_LIST += STORAGE_OPS_25LC1024
#CONFIG_LIST += STORAGE_OPS_24LC128
#CONFIG_LIST += STORAGE_OPS_W25Q256

#CONFIG_LIST += NET_CLIENT_PROTOCOL_UDP
CONFIG_LIST += NET_CLIENT_PROTOCOL_TCP
#CONFIG_LIST += NET_CLIENT_PROTOCOL_TLS

#CONFIG_LIST += NET_CLIENT_REQUEST_DEFAULT
CONFIG_LIST += NET_CLIENT_REQUEST_SSE
#CONFIG_LIST += NET_CLIENT_REQUEST_OCPP_1_6

CONFIG_LIST += CHARGER_CHANNEL_NATIVE
CONFIG_LIST += CHARGER_CHANNEL_PROXY_REMOTE
#CONFIG_LIST += CHARGER_CHANNEL_PROXY_LOCAL
#CONFIG_LIST += POWER_MANAGER_CHANNEL_PROXY_LOCAL

#CONFIG_LIST += DISABLE_DISPLAY
#CONFIG_LIST += DISABLE_CARDREADER
#CONFIG_LIST += DISABLE_POWER_MANAGER
#CONFIG_LIST += DISABLE_VOICE
#CONFIG_LIST += DISABLE_STORAGE
CONFIG_LIST += DISABLE_USB_OTG
#CONFIG_LIST += DISABLE_TRACE
#CONFIG_LIST += LOG_DISABLE

#CONFIG_LIST += MULTI_CHARGE_PROXY

#CONFIG_LIST += CHARGER_BMS_HANDLER_GB
CONFIG_LIST += CHARGER_BMS_HANDLER_GB_V2G
#CONFIG_LIST += CHARGER_BMS_HANDLER_JP
#CONFIG_LIST += CHARGER_BMS_HANDLER_CCS
#CONFIG_LIST += CHARGER_BMS_HANDLER_GB_MULTI_CHARGE
#CONFIG_LIST += CHARGER_BMS_HANDLER_AC
#CONFIG_LIST += CHARGER_BMS_HANDLER_NOBMS

#CONFIG_LIST += CARD_READER_HANDLER_PSEUDO
CONFIG_LIST += CARD_READER_HANDLER_ZLG
#CONFIG_LIST += CARD_READER_HANDLER_MT_318_626
#CONFIG_LIST += CARD_READER_HANDLER_MT_318_628

CONFIG_LIST += ENERGY_METER
CONFIG_LIST += ENERGY_METER_DC
#CONFIG_LIST += ENERGY_METER_AC
#CONFIG_LIST += ENERGY_METER_AC_HLW8032
#CONFIG_LIST += ENERGY_METER_AC_SDM_220
#CONFIG_LIST += ENERGY_METER_AC_SDM_630
#CONFIG_LIST += ENERGY_METER_DCM3366D_J_G

#CONFIG_LIST += POWER_MODULES_HANDLER_NONE
#CONFIG_LIST += POWER_MODULES_HANDLER_PSEUDO
#CONFIG_LIST += POWER_MODULES_HANDLER_HUAWEI
#CONFIG_LIST += POWER_MODULES_HANDLER_INCREASE
#CONFIG_LIST += POWER_MODULES_HANDLER_INFY
#CONFIG_LIST += POWER_MODULES_HANDLER_STATEGRID
#CONFIG_LIST += POWER_MODULES_HANDLER_YYLN
#CONFIG_LIST += POWER_MODULES_HANDLER_WINLINE
#CONFIG_LIST += POWER_MODULES_HANDLER_ZTE
CONFIG_LIST += POWER_MODULES_HANDLER_INFY_V2G

CONFIG_LIST += FUNCTION_BOARD_HANDLER_485
#CONFIG_LIST += FUNCTION_BOARD_HANDLER_V5
#CONFIG_LIST += FUNCTION_BOARD_HANDLER_CUSTOM
#CONFIG_LIST += ENABLE_CXX

$(foreach config_item,$(CONFIG_LIST),$(eval $(addprefix CONFIG_,$(config_item)) := $(config_item)))

CONFIG_CFLAGS := $(addprefix -D,$(CONFIG_LIST))
